import SemanticCache from "../models/SemanticCache.js";
import { embedTexts } from "./gemini.js";

const SIMILARITY_THRESHOLD = 0.90; // Highly similar questions only

// Standard Cosine Similarity function
function cosineSimilarity(vecA, vecB) {
  let dotProduct = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

/**
 * Searches the semantic cache inside MongoDB for similar questions.
 * Runs in-memory cosine similarity search which is extremely fast for hundreds/thousands of cache records.
 * @param {string} userQuery The user's question
 * @returns {Promise<string|null>} The cached answer if found, otherwise null
 */
export async function getSemanticCachedResponse(userQuery) {
  try {
    const trimmedQuery = userQuery.trim();
    if (trimmedQuery.length < 5) return null;

    // 1) First check for exact query match to bypass any embeddings calculations (extra optimization!)
    const exactHit = await SemanticCache.findOne({ question: trimmedQuery }, "answer").lean();
    if (exactHit) {
      console.log(`[Semantic Cache] Exact match hit for: "${trimmedQuery}". Bypassing LLM.`);
      return exactHit.answer;
    }

    // 2) Generate embedding for the incoming user query
    const embeddings = await embedTexts([trimmedQuery]);
    const queryEmbedding = embeddings[0];

    // 3) Retrieve all cache entries
    const cacheEntries = await SemanticCache.find({}, "question answer embedding").lean();
    if (cacheEntries.length === 0) return null;

    let bestMatch = null;
    let highestScore = 0;

    // 4) Compute cosine similarity in memory
    for (const entry of cacheEntries) {
      if (!entry.embedding || entry.embedding.length !== queryEmbedding.length) continue;
      const score = cosineSimilarity(queryEmbedding, entry.embedding);
      if (score > highestScore) {
        highestScore = score;
        bestMatch = entry;
      }
    }

    // 5) Return match if above threshold
    if (highestScore >= SIMILARITY_THRESHOLD && bestMatch) {
      console.log(`[Semantic Cache] Semantic hit: "${bestMatch.question}" -> similarity: ${highestScore.toFixed(3)} (Threshold: ${SIMILARITY_THRESHOLD}). Bypassing AI generation.`);
      return bestMatch.answer;
    }

    console.log(`[Semantic Cache] Cache miss for: "${trimmedQuery}". Best similarity score was: ${highestScore.toFixed(3)}.`);
    return null;
  } catch (error) {
    console.error("[Semantic Cache] Search failed:", error);
    return null;
  }
}

/**
 * Saves a question-answer pair into the semantic cache.
 * @param {string} userQuery The question
 * @param {string} answer The answered generated by AI
 */
export async function saveToSemanticCache(userQuery, answer) {
  try {
    const trimmedQuery = userQuery.trim();
    if (trimmedQuery.length < 5 || !answer || answer.includes("AI service is not configured")) return;

    // Verify if already exists exactly
    const exists = await SemanticCache.findOne({ question: trimmedQuery }).lean();
    if (exists) return;

    // Generate embedding and persist
    const embeddings = await embedTexts([trimmedQuery]);
    const queryEmbedding = embeddings[0];

    await SemanticCache.create({
      question: trimmedQuery,
      answer,
      embedding: queryEmbedding
    });
    
    console.log(`[Semantic Cache] Successfully cached answer for query: "${trimmedQuery}".`);
  } catch (error) {
    // Gracefully handle duplicate key race conditions
    if (error.code === 11000) return;
    console.error("[Semantic Cache] Failed to save to cache:", error);
  }
}
